### ISSUE TITLE
Pre-trained model to test?

### ISSUE THREAD

**Issue by Roowenliang** [HengLan/CGSTVG#1]
Dear Authors,
Great work! 
Are you going to release your pre-trained models for us to try out soon?
Thanks

**Comment by HengLan** [comment]
> Dear Authors, Great work! Are you going to release your pre-trained models for us to try out soon? Thanks

Hi,

Thanks for your interest. Yes, we'll release everything about our method (code and pretrained models). Please stay tuned.

**Comment by HengLan** [comment]
> Dear Authors, Great work! Are you going to release your pre-trained models for us to try out soon? Thanks

Hi 

We have released all the code and models. Thanks for your patience.

**Comment by yunjeongch** [comment]
Dear HengLan, 

Attempting to get pretrained weights, I got the message:

`Access to model Gstar666/CGSTVG is restricted. You must be authenticated to access it.
`
How can I resolve it?

Thanks in advance.
