### ISSUE TITLE
Pre-trained weight inaccessible. 

### ISSUE THREAD

**Issue by steven413d** [HengLan/CGSTVG#12]
Dear Authors,

Attempting to get pretrained weights of VidSTG, I got the message:

Access to model Gstar666/CGSTVG is restricted. You must be authenticated to access it. 
How can I resolve it?

Thank you!

**Comment by zaiquanyang** [comment]
> Dear Authors,
> 
> Attempting to get pretrained weights of VidSTG, I got the message:
> 
> Access to model Gstar666/CGSTVG is restricted. You must be authenticated to access it. How can I resolve it?
> 
> Thank you!

Do you have solved it? I met the same problem..
