### ISSUE TITLE
With each iteration, the model’s video memory gradually increases

### ISSUE THREAD

**Issue by tongzhang111** [HengLan/CGSTVG#2]
With each iteration, the model’s video memory gradually increases

**Comment by GX77** [comment]
I didn't quite understand your question, but I think it's normal for the memory usage to gradually increase in the early stages of training.

**Comment by tongzhang111** [comment]
<img width="838" alt="WeChat4a73b46a7215f6446143ab556d4619d8" src="https://github.com/HengLan/CGSTVG/assets/104766709/bca469b9-78f6-4777-982b-10898d92e7e6">
With each iteration, the max mem gradually increases

**Comment by GX77** [comment]
I understand what you mean now, I didn't notice this situation before, I'm not quite sure about the reason, it might need careful debugging.

**Comment by GX77** [comment]
One speculation is that the image size is dynamic, which would lead to a gradual increase in video memory.

**Comment by tongzhang111** [comment]
老哥，你好，我是山东大学张童。目前也在做时间空间视频定位。我也在您的github进行问题的提问。不知道方便加个微信不。有问题多跟你交流。谢谢！ 微信：18663412198

---- Replied Message ----
From GX ***@***.***> Date 04/03/2024 08:55 To HengLan/CGSTVG ***@***.***> Cc tongzhang111 ***@***.***>,
Author ***@***.***> Subject Re: [HengLan/CGSTVG] With each iteration, the model’s video memory gradually increases (Issue #2)  

One speculation is that the image size is dynamic, which would lead to a gradual increase in video memory.

**Comment by tongzhang111** [comment]
老哥，你好，我是山东大学张童。目前也在做时间空间视频定位。我也在您的github进行问题的提问。不知道方便加个微信不。有问题多跟你交流。谢谢！ 微信：18663412198




---- Replied Message ----
From GX ***@***.***> Date 04/03/2024 08:55 To HengLan/CGSTVG ***@***.***> Cc tongzhang111 ***@***.***>,
Author ***@***.***> Subject Re: [HengLan/CGSTVG] With each iteration, the model’s video memory gradually increases (Issue #2)  

One speculation is that the image size is dynamic, which would lead to a gradual increase in video memory.

**Comment by tongzhang111** [comment]
As the number of iterations increases, the maximum memory also increases. Therefore, the problem of video memory explosion will occur. I determine whether there is a memory leak

**Comment by GX77** [comment]
If the OOM (Out of Memory) error occurs, you may need to reduce the resolution.
