### ISSUE TITLE
How much GPU memory do I need to run the code?

### ISSUE THREAD

**Issue by Hyeongkeun** [HengLan/CGSTVG#4]
Is it possible to run the code on A6000(48GB)? I'm curious what GPUs you used and how many.

**Comment by anonymousA01** [comment]
> 代码可以在A6000(48GB)上运行吗？我很好奇你使用了什么 GPU 以及有多少。

This was likely trained on 8 A100 GPUs. I tried training on a single A100, and it took 10 days for one dataset and 20 days for another. With a batch size of 1, the memory usage was around 60GB.

**Comment by GX77** [comment]
> Is it possible to run the code on A6000(48GB)? I'm curious what GPUs you used and how many.

The smallest HCSTVG-v1 dataset is experimented on a 16 A100 GPUs. If your memory is insufficient, the resolution can be set to 320.
