### ISSUE TITLE
Simple questions about baseline and initialization.

### ISSUE THREAD

**Issue by HenryHZY** [HengLan/CGSTVG#6]
@HengLan @GX77 

Thanks for your great project. 

1. I would like to know how can I reproduce the baseline model.
Take `experiments/hcstvg.yaml` as an example, I am not sure what should I modify in the config to remove the ICG & ICR modules. Could you please provide a config for that?

2. In your paper, "Q_0 and P_0 fed to the first decoding stage are initialized following DETR".
Do you mean that Q_0 and P_0 are initialized with Xavier initialization? Could you share the link to the code? 

Thank you very much!

**Comment by GX77** [comment]
1. Sorry, you cannot reproduce the baseline model just by modifying the yaml file. You need to comment out the code related to ICG & ICR in the code. The simplest way is to set the ‘context’ in link to None. 
https://github.com/HengLan/CGSTVG/blob/f062d84b72aee8be4425a4a5ab20aa5b077ca142/models/grounding_model/query_decoder.py#L290C13-L290C20

**Comment by GX77** [comment]
2.  Just like the previous method, we also initialize the query to all zeros. https://github.com/HengLan/CGSTVG/blob/f062d84b72aee8be4425a4a5ab20aa5b077ca142/models/grounding_model/query_decoder.py#L100

**Comment by HenryHZY** [comment]
Thank you for the detailed responses!
